### ISSUE TITLE
ERROR: can't load server CA file

### ISSUE THREAD

**Issue by fearTheUnknown** [insanum/ktls_test#1]
Hi @insanum,
I would like to report the issue as following:

- OS Distribution: **CentOS Linux release 8.2.2004 (Core)**
- Kernel: **4.18.0-193.28.1.el8_2.aarch64**
- Build Date: **Jan 8th 2021**

**_Description:_**
**tls_client_12** and **tls_client_13** cannot load the server CA file located in **certs/ca-cert.pem**.

**_Steps to reproduce:_**
Run `build.sh` build script
Run `tls_server &` in background
Run `tls_client_12 -s 127.0.0.1`
Run `tls_client_13 -s 127.0.0.1`

**_Expected Result:_**
**tls_client_12** and **tls_client_13** can connect to **tls_server** running in background

**_Real Result:_**
**tls_client_12** and **tls_client_13** both issue error **"ERROR: can't load server CA file"**

The log file during installation and running test is attached in [ktls_log.txt](https://github.com/insanum/ktls_test/files/5790356/ktls_log.txt)

Thank you

**Comment by fearTheUnknown** [comment]
Hi @insanum,

as from the **"ca-cert.pem"** certificate in **"ktls_test/certs/"** :

```
[root@localhost certs]# cat ca-cert.pem
...
            Not Before: Apr 13 15:23:09 2018 GMT
            Not After : Jan  7 15:23:09 2021 GMT
...

```
The **certificates and keys** in **"ktls_test/certs/"** seem to be **out-of-date.**
Could you help to re-generate the new ones ?

Thank you for your help

**Comment by insanum** [comment]
Thanks for reporting this. These cert files are directly from wolfSSL so you can copy in the updated files as follows:

```
cd certs
rm *.pem
wget https://raw.githubusercontent.com/wolfSSL/wolfssl/master/certs/ca-cert.pem
wget https://raw.githubusercontent.com/wolfSSL/wolfssl/master/certs/server-cert.pem
wget https://raw.githubusercontent.com/wolfSSL/wolfssl/master/certs/server-key.pem
```

I should probably just remove the copies in ktls_test and point the code directly to those cert files under wolfSSL/.  :-)

**Comment by fearTheUnknown** [comment]
Glad that i can help ;)

By the way, could you help to update the fix to the **master** branch?

I would like to check if the tool is going to function properly. If it is, the issue should be closed then.

This is such a good simple tool for testing the kTLS Offload function of the NIC cards for non-specialist users.

Thank you for your help and reply.

**Comment by insanum** [comment]
The certificate was updated.
